services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - mongo
  mongo:
    image: mongo
    command: "--bind_ip_all"
    ports:
      - "27017:27017"
    expose:
      - "27017/tcp"
      - "27017/udp"
    volumes:
      - "databaseVolume:/data/db"
volumes:
  logvolume01: { }
  databaseVolume: { }